<?php
/**
 * Created by JetBrains PhpStorm.
 * User: ivashka
 * Date: 3/16/13
 * Time: 8:30 PM
 * To change this template use File | Settings | File Templates.
 */
$infoItem = getOneString("SELECT * FROM `ls_items` where `id` = '".intval($_GET['id'])."';");

$infoCardParam = mysql_fetch_array(mysql_query("SELECT * FROM `ls_cardparam` WHERE `id_card` = '".$infoItem['id_card']."' and `db_type` = 'image'"), MYSQL_ASSOC);
if (isset ($_COOKIE['accessLevel']) and $_COOKIE['accessLevel']==100)
{
    $admin_menu .= '
    <style type="text/css">
    .adminMenu {
        position: fixed;
        bottom:0px;
    }
.adminButton {
	-moz-box-shadow:inset 0px 1px 0px 0px #ffffff;
	-webkit-box-shadow:inset 0px 1px 0px 0px #ffffff;
	box-shadow:inset 0px 1px 0px 0px #ffffff;
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #ededed), color-stop(1, #dfdfdf) );
	background:-moz-linear-gradient( center top, #ededed 5%, #dfdfdf 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=\'#ededed\', endColorstr=\'#dfdfdf\');
	background-color:#ededed;
	-moz-border-radius:6px;
	-webkit-border-radius:6px;
	border-radius:6px;
	border:1px solid #dcdcdc;
	display:inline-block;
	color:#000000;
	font-family:arial;
	font-size:15px;
	font-weight:bold;
	padding:0px 24px;
	text-decoration:none;
	text-shadow:1px 1px 0px #ffffff;
}.adminButton:hover {
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #dfdfdf), color-stop(1, #ededed) );
	background:-moz-linear-gradient( center top, #dfdfdf 5%, #ededed 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=\'#dfdfdf\', endColorstr=\'#ededed\');
	background-color:#dfdfdf;
}.adminButton:active {
	position:relative;
	top:1px;
}
/* This imageless css button was generated by CSSButtonGenerator.com */
</style>
    <div class="adminMenu">
        <a href="'.$config['site_url'].'admin/" class="adminButton" target="_blank">Админ панель</a>
        <a href="'.$config['site_url'].'admin/index.php?do=products&action=edit_item&id='.intval($_GET['id']).'" class="adminButton" target="_blank">Редактировать</a>
        <a href="'.$config['site_url'].'admin/add_image.php?id='.$infoItem['id_card'].'&id_param='.$infoCardParam['id'].'&id_item='.intval($_GET['id']).'" class="adminButton" target="_blank">Управление фото</a>
        <a href="'.$config['site_url'].'admin/index.php?do=orders" class="adminButton" target="_blank">Заказы</a>
        <a href="'.$config['site_url'].'ru/mode/item-'.intval($_GET['id']).'.html?new=1" class="adminButton">Оновлення</a>
    </div>
    ';
    if (isset ($_GET['new'])){
        mysql_query("UPDATE `ls_items` set `time` = '".time()."' WHERE `id` = '".intval($_GET['id'])."';");
    }
}
mysql_query("update `ls_items` set `visit` = `visit` + 1 where `id` = '".intval($_GET['id'])."';");
$sql = "SELECT COUNT(*) FROM `ls_items` where `text_1` = '".mysql_real_escape_string($infoItem['text_1'])."' and (`select_1` <> '' or `select_10` <> '' or `select_11` <> '' or `select_12` <> '' or `select_15` <> '' or `select_18` <> '');";
$infoCountOtherColor = mysql_fetch_array(mysql_query($sql), MYSQL_ASSOC);
$infoAllPhoto = getAllPhotoItem($infoItem['id']);
$itemImagesMobile = '';
if ($infoAllPhoto)
{
    $smallImage = '';
    $smallImageMobile = '';
    $smallImageBlock = '';
    $i = 0;
    foreach ($infoAllPhoto as $key => $v)
    {
            $active = '';
            if ($i == 0)
                $active = ' active';
            //            $smallImage .= '<div class="row">';
//            $smallImage .= '
//            <div class="col-xs-3" style="cursor:pointer;">
//                <a href="' . $config ['site_url'] . 'resize_image.php?filename=' . urlencode($v['value']) . '&const=130&width=1280&height=800&r=255&g=255&b=255" onclick="return false;" rel="prettyPhoto[fullImage]" class="thumbnail">
//                    <img src="' . $config ['site_url'] . 'resize_image.php?filename=' . urlencode($v['value']) . '&const=130&width=200&height=200&r=255&g=255&b=255" width="200" height="200">
//                </a>
//            </div>';
//        <li>
//									<div class="blog_single_carousel">
//										<a class="active" data-bs-toggle="tab" href="#tab1"><img src="{template}img/product/blog-big-1.jpg" alt=""></a>
//									</div>
//								</li>
//								<li>
//									<div class="blog_single_carousel">
//										<a data-bs-toggle="tab" href="#tab2"><img src="{template}img/product/blog-big-2.jpg" alt=""></a>
//									</div>
//								</li>
            $smallImageBlock .= ' <li>
                        <div class="blog_single_carousel">
                            <a '.(($key==0) ? 'class="active"' : '').' data-bs-toggle="tab" href="#tab'.($key+1).'">
                                <img src="' .getImageFile($v['value'], 835, 1000, 130). '" data-fancybox-group="gallery" title="'.$infoItem['text_1'].'">
                           
                                </a>
                        </div>
                    </li>';
        $blockImage .= '
            <div class="tpproduct-details__list-img-item">
                <img src="' .getImageFile($v['value'], 700, 800, 130). '" title="'.$infoItem['text_1'].'">
             </div>
            ';
            if ($key==0){
                $bigPhotoBlock .= '<div id="tab'.($key+1).'" class="tab-pane fade show active">
								<div class="blog_tabs">
									<a class="fancybox" href="' . $config ['site_url'] . 'upload/userparams/' .$v['value'] . '" data-fancybox-group="gallery" title="'.$infoItem['text_1'].'">
									    <img src="' .getImageFile($v['value'], 835, 1000, 130). '" alt="'.$infoItem['text_1'].'">
                                    </a>
								</div>
							</div>
							';
            } else {
                $bigPhotoBlock .= '
                <div id="tab'.($key+1).'" class="tab-pane fade">
                    <div class="blog_tabs">
                        <a class="fancybox" href="' . $config ['site_url'] . 'upload/userparams/' .$v['value'] . '" data-fancybox-group="gallery" title="'.$infoItem['text_1'].'">
                        <img src="' .getImageFile($v['value'], 835, 1000, 130). '" alt=""></a>
                    </div>
                </div>

                ';
            }
//            $bigPhotoBlock .= '
//            <div id="tab'.($key+1).'" class="tab-pane fade '.(($key==0) ? ' show active' : '').'">
//                <div class="blog_tabs">
//                    <a class="fancybox" href="' . $config ['site_url'] . 'resize_image.php?filename=' . urlencode($v['value']) . '&const=130&width=835&height=1000&r=255&g=255&b=255" data-fancybox-group="gallery" title="'.$infoItem['text_1'].'"><img src="' . $config ['site_url'] . 'resize_image.php?filename=' . urlencode($v['value']) . '&const=130&width=835&height=1000&r=255&g=255&b=255" alt="'.addslashes($infoItem['text_1']).'"></a>
//                </div>
//            </div>
//            ';
            if (MOBILEVER == 1) {
                $active = '';
                if ($key == 0)
                    $active = ' active';
                $itemImagesMobile .= '
                <div class="item">
                  <img src="' . $config ['site_url'] . 'resize_image.php?filename=' . urlencode('upload/userparams/' . $v['value']) . '&const=130&width=640&height=480&r=255&g=255&b=255" alt="' . $infoItem['text_1'] . '">
                </div>
                ';
            }
            $i++;
            if ($i == 4 or !isset ($infoAllPhoto[$key + 1])) {
                //            $smallImage .= '</div>';
                $i = 0;
            }
        }
        $smallImageMobile .= '
                        <div class="item'.(($key==0) ? ' active' : '').'">
                            <a href="#" class="thumbnail"><img src="' . $config ['site_url'] . 'resize_image.php?filename=' . urlencode($v['value']) . '&const=130&width=640&height=480&r=255&g=255&b=255" width="640" height="480"></a>
                        </div>
                    ';
}
if (strlen($infoItem['text_6'])>0 and MOBILEVER==0){
    $explodeYt = explode ('v=', $infoItem['text_6']);
    //$smallImage .= '<div class="oneImageSmall" style="cursor:pointer;"><img src="https://i.ytimg.com/vi/'.$explodeYt[1].'/default.jpg" width="106" height="106"  onclick="setMainVideo(\''.$explodeYt[1].'\');"></div>';
    $smallImage .= '
    <div class="col-xs-3" style="cursor:pointer;">
        <a href="https://www.youtube.com/watch?v='.$explodeYt[1].'" onclick="return false;" rel="prettyPhoto[fullImage]" class="thumbnail">
            <img src="'.$config ['site_url'].'images/ytplay.png">
        </a>
    </div>
    ';
    $smallImageMobile .= '
    <div class="item">
        <iframe src="https://www.youtube.com/embed/'.$explodeYt[1].'?rel=1&amp;autoplay=1" width="100%" height="344" frameborder="no"></iframe>
    </div>
                    ';
}
if (strlen($infoItem['text_4'])>0)
{
    $infoItemBody = '
    <div class="infoItemBlock">
        <div class="infoItemHeader">Описание товара:</div>
        <div class="textInfoItem">
            '.$infoItem['text_4'].'
        </div>
    </div>
    ';
}
switch ($infoItem['select_6'])
{
    case 46:
        $allSize = getValuesSelectParam(1);
        $idSize = 1;
        $isKross = 1;
        break;
    case 47:
        $allSize = getValuesSelectParam(11);
        $idSize = 11;
        break;
    case 48:
        $allSize = getValuesSelectParam(10);
//        print_r ($allSize);
        $idSize = 10;
        break;
    case 100:
        $allSize = getValuesSelectParam(12);
        $idSize = 12;
        break;
    case 126:
        $allSize = getValuesSelectParam(15);
        $idSize = 15;
        $isKross = 1;
        break;
    case 128:
        $allSize = getValuesSelectParam(18);
        $idSize = 18;
        $isKross = 1;
        break;
}
$sizeItem = json_decode($infoItem['select_'.$idSize], true);
//usort($allSize, "compare");
function compare ($v1, $v2) {
    /* Сравниваем значение по ключу text */
    if ($v1["text"] == $v2["text"]) return 0;
    return ($v1["text"] < $v2["text"])? -1: 1;
}
$allSizeHtml .= '<script type="text/javascript">
  $(document).ready(function () {
    $("[rel=tooltip]").tooltip();
  });
</script>';
foreach ($allSize as $v)
{
    if (!in_array($v['id'], $sizeItem) and $v['id']!=$sizeItem){
        $dopClass = 'oneSizeItemDisable';
    } else {
        $dopInput = '<input type="hidden" name="select|'.$v['id'].'" value="0" class="sizeUser">';
        $dopInputBuyOneClick = '<input type="hidden" name="select|'.$v['id'].'" value="0" class="sizeUserBuyOneClick">';
    }
    switch ($v['text']){
        case 7:
            $sm = '25';
            break;
        case 7.5:
            $sm = '25,5';
            break;
        case 8:
            $sm = '26';
            break;
        case 8.5:
            $sm = '26,5';
            break;
        case 9:
            $sm = '27';
            break;
        case 9.5:
            $sm = '27,5';
            break;
        case 10:
            $sm = '28';
            break;
        case 10.5:
            $sm = '28,5';
            break;
        case 11:
            $sm = '29';
            break;
        case 11.5:
            $sm = '29,5';
            break;
        case 12:
            $sm = '30';
            break;
        case 12.5:
            $sm = '30,5';
            break;
        case 13:
            $sm = '31';
            break;
        case 13.5:
            $sm = '31,5';
            break;
        case 14:
            $sm = '32';
            break;
        case 14.5:
            $sm = '32,5';
            break;
        case 15:
            $sm = '33';
            break;
        case 16:
            $sm = '34';
            break;
        case 17:
            $sm = '35';
            break;
        case "MISC":
            $sm = 'Этот товар производится в одном размере.';
            break;
    }
    if ($infoItem['select_6']==46 or $infoItem['select_6']==48 or $infoItem['select_6']==47){
        if (strlen($sm)>0){
            if ($v['text']!='MISC')
                $sm .= ' см.';
            $allSizeHtml .= '<div class="oneSizeItem '.$dopClass.'" data-placement="top" rel="tooltip" data-original-title="'.$sm.'">'.$v['text'].$dopInput.'</div>';
        } else {
            $allSizeHtml .= '<div class="oneSizeItem '.$dopClass.'">'.$v['text'].$dopInput.'</div>';
        }
    } else {
        $allSizeHtml .= '<div class="oneSizeItem '.$dopClass.'">'.$v['text'].$dopInput.'</div>';
    }
    $allSizeBuyOneClick .= '<div class="oneSizeItem '.$dopClass.'">'.$v['text'].$dopInputBuyOneClick.'</div>';
    unset ($dopClass, $dopInput, $dopInputBuyOneClick, $sm);
}
$js_script .= '
$(document).ready(function() {
    $(".oneSizeItem").click(function(){
        $(".sizeUser").val(0);
        $(".oneSizeItemActive").removeClass("oneSizeItemActive");
        if (!$(this).hasClass("oneSizeItemDisable")){
            $(this).toggleClass("oneSizeItemActive");
            $(this).find("input").val(1);
        }
    });

});
';
/*
 * $(".addToCart").click(function(){
            $("#selectSizeBlock").hide(150);
            $.ajax({
                type: \'POST\',
                dataType: \'html\',
                url: \'https://gasalmaz.com.ua/include/ajax/addItemToCart.php\',
                data: {
                    idItem: '.intval($_GET['id']).'
                },
                success: function(result) {
                    $("#addItemToCartBlock").html(result);
                    getCartBlock();
                },
            });
    });
 */

if ($infoCountOtherColor['COUNT(*)']>1)
{
    $infoCountOtherColor = getAllSimilarItem($infoItem['text_1']);
    $otherColor = '
    <div class="selectColorItem" style="margin: 20px 0px;">
        <div style="width: 100%; padding: 5px 0px; background: #0e0e0e; color: #FFF; text-align: center;">Выберите цвет</div>
    ';
    foreach ($infoCountOtherColor as $v)
    {
        if ($v['id']==intval($_GET['id']))
        {
            $addClass = ' otherColorActive';
        } else {
            $addClass = ' otherColorPassive';
            $linkFirst = '<a href="'.generateItemLink ($v['id']).'">';
            $linkSecond = '</a>';
        }
        $new = '';
        if (time()-$v['time']<2678400){
            $new = '<div class="new"><img src="https://og-shop.in.ua/images/new.png"></div>';
        }
        $otherColor .= '<div class="oneImageSmall'.$addClass.'" style="position: relative;">
                            '.$linkFirst.'<img src="'.$config ['site_url'].'resize_image.php?filename='.urlencode('upload/userparams/'.getMainImage ($v['id'])).'&const=130&width=106&height=106&r=255&g=255&b=255" width="106" height="106" alt="small">'.$linkSecond.'
                            '.$new.'
                        </div>';
        unlink ($linkFirst, $linkSecond);
    }
    $otherColor .= '</div>';
}
//<a href="images/examples/image-3.jpg" rel="lightbox[plants]" title="Click on the right side of the image to move forward."><img src="images/examples/thumb-3.jpg" alt="Plants: image 1 0f 4 thumb" /></a>
if ($isKross)
{
    if (MOBILEVER==0){
        $imgKross = '<img src="'.$config['site_url'].'images/razm.jpg" alt="Размеры">';
    } else {
        $imgKross = '<a href="'.$config['site_url'].'images/razm.jpg" target="_blank">посмотреть размерную сетку</a>';
    }
}
$infoNal = mysql_fetch_array (mysql_query("SELECT * FROM `ls_translate` where `id_elements` = '".$infoItem['select_4']."' and `type` = 'select_value';"), MYSQL_ASSOC);
$sql = "
    SELECT 
        `ls_giftToItem`.* 
    FROM 
        `ls_giftToItem`
    LEFT JOIN
        `ls_cart`
    ON 
        `ls_cart`.`id_item` = `ls_giftToItem`.`itemId`
    WHERE 
        `ls_giftToItem`.`giftId` = '".$infoItem['id']."' 
    AND 
        `ls_giftToItem`.`price` != '0.01'
    AND
        `ls_giftToItem`.`dateFrom` <= '".date("Y-m-d")."'
    AND
        `ls_giftToItem`.`dateTo` >= '".date("Y-m-d")."'
    AND `ls_cart`.`uniq_user` = '".$_COOKIE['PHPSESSID']."'
    AND `ls_cart`.`status` = 0
        ";
//if ($_COOKIE['accessLevel']==100) {
    if ($infoGift = getOneString($sql)) {
        $infoItem['price_2'] = $infoGift['price'];
    }
//}
$sql = "
    SELECT 
        `ls_giftToItem`.* 
    FROM 
        `ls_giftToItem`
    WHERE 
        `ls_giftToItem`.`giftId` = '".$infoItem['id']."' 
    AND 
        `ls_giftToItem`.`price` != '0.01'
    AND
        `dateFrom` <= '".date("Y-m-d")."'
    AND
        `dateTo` >= '".date("Y-m-d")."'
        ";
$giftAll = '';
if ($infoGiftAll = getOneString($sql)){
    if ($infoMainItem = getOneString("SELECT * FROM `ls_items` WHERE `id` = '".$infoGiftAll['itemId']."'")) {
        $giftAll = '<div class="row"><div class="col-lg-12" style="background-color: #12aedf; color:#FFF;-webkit-border-top-left-radius: 5px;
-webkit-border-top-right-radius: 5px;
-moz-border-radius-topleft: 5px;
-moz-border-radius-topright: 5px;
border-top-left-radius: 5px;
border-top-right-radius: 5px;">
            Разом дешевше! Цей товар Ви можете придбати зі знижкою, купуючи його з <a href="/ua/mode/item-'.$infoMainItem['id'].'.html" style="color:#FFF; text-decoration: underline;">'.$infoMainItem['text_1'].' '.getOneValueText($infoMainItem['select_1']).' '.$infoMainItem['text_4'].'</a> 
        </div></div>';
    }
}
if ($infoItem['price_2']==0 or $infoItem['price_1']==$infoItem['price_2'])
{
    $priceHtml = '<div class="priceItem"><span class="priceNow"><span id="priceInt">'.$infoItem['price_1'].'</span> грн.</span>
    <span itemprop="price" content="'.$infoItem['price_1'].'"></span></div>';
    $priceHtml = '<p class="rating_dollor rating_margin"><span class="rating_value_two">'.$infoItem['price_1'].' грн.</span></p>';
} else {
    $priceHtml = '<div class="priceItem" style="margin-top: -23px;"><span class="priceNow" style="font-size: 14px;"><span style="text-decoration: line-through; font-size: 14px;" id="priceOld">'.$infoItem['price_1'].'</span></div>
    <div class="priceItem" style="display: inline-block;"><span class="priceNow" style="font-size: 28px;"><span id="priceInt">'.$infoItem['price_2'].'</span>  грн.</div>
    <span itemprop="price" content="'.$infoItem['price_2'].'">';
    $priceHtml = '<p class="rating_dollor rating_margin"><span class="rating_value_one dollor_size">'.$infoItem['price_1'].'</span> <span class="rating_value_two">'.$infoItem['price_2'].' грн.</span></p>';
}
$priceHtml .= '<link itemprop="availability" href="https://schema.org/InStock"/>';
$art = '';
if (strlen($infoItem['text_11'])>0){
    $art = $infoItem['text_11'];
}
$title = getNameItem($infoItem).' на domajor.com.ua';
$description = $infoItem['text_1'].' купити в Украине. Доставка наложенным платежем по всей територии Украины.';
$keywords = $infoItem['text_1'].' купити, продажа '.$infoItem['text_1'].', продажа '.$infoItem['text_1'].' в Украине';
if ($infoItem['select_6']!=46 and strlen($infoItem['select_7'])>0)
    $select_7Sql = "and
        `select_7` = '".$infoItem['select_7']."'";
$percent = ceil($infoItem['price_1']/100*15);
$sql = "
    SELECT * FROM
        `ls_items`
     where
        `select_6` = '".$infoItem['select_6']."'
        ".$select_7Sql."
        ".$select_8Sql."
    and
        `select_4` = 42
    and
        (`select_1` <> '' or `select_10` <> '' or `select_11` <> '' or `select_12` <> '')
        ORDER by RAND()
     LIMIT 0, 24;";
if ($arrayRotatorItem = getArray($sql)){
    $i = 0;
    $htmlTemplate = file_get_contents($config ['site_url'].'templates/'.$config ['default_template'].'/oneItemRotator.html');
    if (MOBILEVER==1){
        $keyMobile = 1;
    } else {
        $keyMobile = 4;
    }
    foreach ($arrayRotatorItem as $key => $v){
        $active = '';
        $oneItem = $htmlTemplate;
        if ($key==0)
            $active = ' active';
        if ($i==0)
            $oneItem = '<div class="item'.$active.'">'.$oneItem;
        $oneItem = str_replace('{name}', $v['text_1'], $oneItem);
        $oneItem = str_replace('{price}', $v['price_1'], $oneItem);
        $oneItem = str_replace('{link}', generateItemLink ($v['id']), $oneItem);
        if ($v['price_2']!=0 and $v['price_2']!=$v['price_1'])
        {
            $oneItem = str_replace('{strike}', '<span style="text-decoration: line-through; color:#7c7c7c; font-size: 16px;">', $oneItem);
            $oneItem = str_replace('{/strike}', '</span>', $oneItem);
            $oneItem = str_replace('{price_discount}', '<span>'.$v['price_2'].'</span>', $oneItem);
        } else {
            $oneItem = str_replace('{strike}', '', $oneItem);
            $oneItem = str_replace('{/strike}', '', $oneItem);
            $oneItem = str_replace('{price_discount}', '', $oneItem);
        }
        if (time()-$v['time']<2678400){
            $oneItem = str_replace('{new}', '<div class="new"><img src="https://og-shop.in.ua/images/new.png"></div>', $oneItem);
        } else {
            $oneItem = str_replace('{new}', '', $oneItem);
        }
        $oneItem = str_replace('{image}', $config ['site_url'].'resize_image.php?filename='.urlencode('upload/userparams/'.getMainImage ($v['id'])).'&const=128&width=172&height=172&r=255&g=255&b=255', $oneItem);
        $i++;
        if (!isset ($arrayRotatorItem[$key+1]) or $i==$keyMobile) {
            $oneItem .= '</div>';
            $i = 0;
        }
        $rotatorItem .= $oneItem;
    }
    $rotatorHtml = '
    <div style="margin: 15px 0px;">
    <div class="infoItemHeader" style="margin: 5px 0px;">Похожие товары</div>
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            '.$rotatorItem.'
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    </div>
    ';
}
//if ($infoItem['select_4']==42){
$dostavka = '
    <div class="alert alert-info">
        <div class="row-fluid">
            <div class="span3"><img src="https://og-shop.in.ua/templates/og-shop/images/1402668315_diagram_v2-32.png"></div>
            <div class="span9">
                <div style="padding-left: 10px;">
                    <p><img src="https://og-shop.in.ua/templates/og-shop/images/camera_test_2033.png"> Доставка 1-2 дня</p>
                    <p><img src="https://og-shop.in.ua/templates/og-shop/images/camera_test_2033.png"> Оплата при получении</p>
                    <p><img src="https://og-shop.in.ua/templates/og-shop/images/camera_test_2033.png"> Гарантия возврата, если не подошел размер</p>
                </div>
            </div>
        </div>
    </div>
    ';
//}
$infoRazm = mysql_fetch_array(mysql_query("SELECT * FROM `ls_params_select_values` WHERE `id` = '".$infoItem['select_19']."';"), MYSQL_ASSOC);
$body = '
<div class="modal hide fade" id="buyOneClickModal">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Купить '.$infoItem['text_1'].' в один клик</h3>
  </div>
  <div class="modal-body" id="buyOneClickModalBody">
    <div class="selectColorItemHeader">Выберите размер</div>
        '.$allSizeBuyOneClick.'
    <div style="text-align: center; display:none; color: #FF0000; font-weight: bold;" id="selectSizeBlockBuyOne">Выберете размер, для покупки</div>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn btn-primary" onclick="buyOneClick();" id="buttonBuyOneClick">Купить</a>
  </div>
</div>
<script>
function ShowModalOneClick(){
    if ($("#userPhone").val().length>0){
        $("#buyOneClickModal").modal("show");
    } else {
        alert ("Введите свой номер мобильного!");
    }
}
function buyOneClick(){
    var param;
        var j = 0;
        $(".sizeUserBuyOneClick").each(function(i, elem){
            if ($(this).val()==1)
            {
                param = ($(this).attr("name"));
                j = j + 1;
            }
        });
        if (!param)
        {
            $("#selectSizeBlockBuyOne").show(150);
        } else {
            $("#selectSizeBlockBuyOne").hide(150);
        $.ajax({
            type: "POST",
            url: "https://og-shop.in.ua/include/ajax/buyOneClick.php",
            data: {
                id: '.$infoItem['id'].' ,
                userPhone: $("#userPhone").val(),
                param: param,
            },
            dataType: \'html\',
            success: function(result) {
                $("#buyOneClickModalBody").html(result);
                $("#buttonBuyOneClick").remove();
            },
        });
        }

}
</script>
<div class="leftColumnItem">
        <div class="origItem" id="mainImage">
            <a href="'.$config ['site_url'].'upload/userparams/'.getMainImage ($infoItem['id']).'" rel="lightbox[plants]"><img src="'.$config ['site_url'].'resize_image.php?filename='.urlencode('upload/userparams/'.getMainImage ($infoItem['id'])).'&const=129&width=630&height=420&r=255&g=255&b=255" width="630" height="420" alt="'.$infoItem['text_1'].'"></a>
            '.$fullImageLink.'
        </div>
        <div class="imageSmall">
            '.$smallImage.'
        </div>
    </div>
    <div class="rightColumnItem">
        <div class="nameItemFull">'.$infoItem['text_1'].'</div>
        <div class="articulItem">Артикул: '.$infoItem['text_2'].'</div>
        <div class="nalItem">Наличие: '.$infoNal['text'].'</div>
        <div class="priceItemFull">'.$priceHtml.'</div>
        <div class="alert alert-info">
            <div class="input-prepend">
              <input type="text" id="userPhone" placeholder="Ваш телефон" class="add-on"><button class="btn btn-success" onclick="ShowModalOneClick();">купить в один клик</button>
            </div>
        </div>
        '.$dostavka.'
        '.$otherColor.'
        <div class="selectColorItemHeader">Выберите размер</div>
        '.$allSizeHtml.'

        <div style="text-align: center; display:none; color: #FF0000; font-weight: bold;" id="selectSizeBlock">Выберете размер, для добавления в корзину</div>
        <div style="text-align: center;" id="addItemToCartBlock"><div class="addToCart">Добавить в корзину</div></div>
    </div>
    <div style="clear:both;"></div>
    '.$infoItemBody.'
    '.$infoRazm['text'].'
    <div style="text-align:center;">'.$imgKross.'</div>
    <div style="clear:both;"></div>
    '.$rotatorHtml.'
'.$admin_menu;
$category = getOneValue($infoItem['select_6']);
$infoCountMarkModel = getOneString("SELECT COUNT(*) FROM `ls_markModel` where `idItem` = '".$infoItem['id']."';");
if ($infoCountMarkModel['COUNT(*)']>0){
    $infoMarkModel = getOneString("SELECT * FROM `ls_markModel` where `idItem` = '".$infoItem['id']."' LIMIT 0,1;");
    $mark = getOneValue($infoMarkModel['mark']);
    $model = getOneValue($infoMarkModel['model']);
    $addBreadcrumbs = '
    <li><a href="'.$config['site_url'].'ru/producer/'.translit($mark['text']).'/'.$infoMarkModel['mark'].'">'.'Чехлы для '.$mark['text'].'</a></li>
    <li><a href="'.$config['site_url'].'ru/producer/'.translit($model['text']).'/'.$infoMarkModel['mark'].'/'.$infoMarkModel['model'].'">'.'Чехлы для '.$mark['text'].' '.$model['text'].'</a></li>
    ';
}
$onlyAdmin = '';
if (isset ($_COOKIE['accessLevel']) and $_COOKIE['accessLevel']==100)
    $onlyAdmin = 'Оновлення ціни - '.date('d.m.Y H:i', $infoItem['text_15']);
$infoItemMark = getOneString("SELECT * FROM `ls_markModel` WHERE `idItem` = '".$infoItem['id']."' LIMIT 0,1;");
$infoCountMarkModel = getOneString("
    SELECT
      COUNT(*)
    FROM
        `ls_items`
    JOIN
      `ls_markModel`
    ON
      `ls_markModel`.`idItem` = `ls_items`.`id`
    WHERE
      `ls_markModel`.`mark` = '".$infoItemMark['mark']."'
    AND
        `ls_markModel`.`model` = '".$infoItemMark['model']."'
        ");
if ($arrayRotatorItem = getArray("
    SELECT
      `ls_items`.*
    FROM
        `ls_items`
    JOIN
      `ls_markModel`
    ON
      `ls_markModel`.`idItem` = `ls_items`.`id`
    WHERE
      `ls_markModel`.`mark` = '".$infoItemMark['mark']."'
    AND
        `ls_markModel`.`model` = '".$infoItemMark['model']."'
        ")){
    $i = 0;
    $j = 0;
    $htmlTemplate = file_get_contents($config ['site_url'].'templates/'.$config ['default_template'].'/oneItemRotator.html');
    foreach ($arrayRotatorItem as $key => $v){
        if ($j==0)
            $active = ' active';
        if ($i == 0){
            $rotatorItem .= '
            <div class="item'.$active.'">
                <ul class="thumbnails" style="list-style: none;">
            ';
        }
        $oneItem = $htmlTemplate;
        $oneItem = str_replace('{id}', $v['id'], $oneItem);
        $oneItem = str_replace('{name}', $v['text_1'], $oneItem);
        $oneItem = str_replace('{price}', getPrice($v['price_1']), $oneItem);
        $oneItem = str_replace('{strike}', '', $oneItem);
        $oneItem = str_replace('{/strike}', '', $oneItem);
        $oneItem = str_replace('{price_discount}', '', $oneItem);
        $oneItem = str_replace('{link}', getItemLink($v), $oneItem);
        $oneItem = str_replace('{image}', $config ['site_url'].'resize_image.php?filename='.urlencode('upload/userparams/'.getMainImage ($v['id'])).'&const=128&width=250&height=250&r=255&g=255&b=255', $oneItem);
//        $items .= $oneItem;
        $rotatorItem .= '
            <li class="col-md-3">
                <div class="thumbnail" style="margin: 0px 5px;">
                '.$oneItem.'
                </div>
            </li>
        ';
        $i++;
        if ($i==4 or !isset ($arrayRotatorItem[$key+1])){
            $i = 0;
            $rotatorItem .= '
                </ul>
            </div>
            ';
        }
        $j++;
        unset ($active);
    }
    $rotatorHtml = '
    <hr>
    <div class="row-fluid" style="margin-bottom: 20px;">
            <div class="col-md-12">
                <script type="text/javascript">
                  $(document).ready(function() {
                    $(\'.carousel\').carousel();
                  });
                </script>
                <div style="font-weight: bold; font-size: 16px; margin: 20px 0px 20px 0px;">Похожие товары ['.$infoCountMarkModel['COUNT(*)'].']  [Покупая несколько товаров - Вы экономите на доставке]:</div>
                    <div class="row-fluid">
                    <div class="carousel slide" id="myCarousel">
                        <div class="carousel-inner">
                          '.$rotatorItem.'
                        </div>
                        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev" style="background-image: none;">
                            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                          </a>
                          <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next" style="background-image: none;">
                            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                          </a>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    ';
}
$description = $infoItem['text_8'];
$buttonBuy = '';
if ($infoItem['text_14']==1){
    $dost = '';
    switch ($infoItem['id_card']){
        case 1:
            $dost = 'доставка 2-4 дня';
            break;
        case 2:
            $dost = 'доставка 1-2 дня';
            break;
        case 3:
            $dost = 'доставка 2-3 дня';
            break;
    }
    $inStock = '
    <div style="font-weight: bold;">'.$dost.'</div>
    <div class="label label-success">Доступен для заказа</div>';
    $buttonBuy = '
    <div class="input-group" style="margin-bottom: 5px;">
      <span class="input-group-btn">
        <button class="btn btn-default btn-xs" type="button" onclick="numberItem(0);"><i class="fa fa-arrow-down" style="font-size: 22px;"></i></button>
      </span>
      <input type="text" class="form-control" value="1" style="text-align: center; height: 30px;" id="number">
      <span class="input-group-btn">
        <button class="btn btn-default  btn-xs" type="button" onclick="numberItem(1);"><i class="fa fa-arrow-up" style="font-size: 22px;"></i></button>
      </span>
    </div>
    <button class="btn btn-success" class="addToCart"><i class="fa fa-cart-plus"></i> КУПИТЬ</button>';
} else {
    $inStock = '<span class="label label-danger">Нет в наличии</span>';
}
$origin = '<meta property="og:image" content="'.$config ['site_url'].'upload/userparams/'.getMainImage ($infoItem['id']).'">';
$brand = getOneValue($infoItem['select_3']);
$dostavka = '';
if ($infoItem['select_4']==42){
    $dostavka = '
        <div class="row">
            <div class="col-lg-3" style="text-align: right;"><i class="fa fa-truck" aria-hidden="true" style="font-size: 72px; color: #c52d2f;"></i></div>
            <div class="col-lg-9">
                <div style="padding-left: 10px;">
                    <p><i class="fa fa-check" aria-hidden="true" style="color: #c52d2f;"></i> Доставка 1-2 дня</p>
                    <p><i class="fa fa-check" aria-hidden="true" style="color: #c52d2f;"></i> Оплата при получении</p>
                    <p><i class="fa fa-check" aria-hidden="true" style="color: #c52d2f;"></i> Гарантия возврата, если не подошел размер</p>
                </div>
            </div>
        </div>
    ';
} else {
    $dostavka = '
        <div class="row">
            <div class="col-lg-3"><i class="fa fa-truck" aria-hidden="true" style="font-size: 72px; color: #c52d2f;"></i></div>
            <div class="col-lg-9">
                <div style="padding-left: 10px;">
                    <p><i class="fa fa-check" aria-hidden="true" style="color: #c52d2f;"></i> Оплата при получении</p>
                    <p><i class="fa fa-check" aria-hidden="true" style="color: #c52d2f;"></i> Гарантия возврата, если не подошел размер</p>
                </div>
            </div>
        </div>
    ';
}
$js_script .= '
$(document).ready(function() {
    $(".oneSizeItem").click(function(){
        $(".sizeUser").val(0);
        $(".oneSizeItemActive").removeClass("oneSizeItemActive");
        if (!$(this).hasClass("oneSizeItemDisable")){
            $(this).toggleClass("oneSizeItemActive");
            $(this).find("input").val(1);
            $("#priceInt").html($("#priceId_" + $(this).attr("id")).val());
            $("#priceOld").html($("#priceOldId_" + $(this).attr("id")).val());
            $("#idItemSize").val($(this).attr("id"));
        }
    });
    $(".addToCart").click(function(){
        gtag_report_conversion();
        gtag(\'event\', \'add_to_cart\', {
            \'send_to\': \'AW-462132080\',
            \'items\': [{
              \'id\': \''.intval($infoItem['id']).'\',
              \'google_business_vertical\': \'retail\'
            }]
          });
        addToCartGA({name: \''.addslashes($infoItem['text_1']).' '.addslashes(getOneValueText($infoItem['select_1'])).' '.addslashes($infoItem['text_4']).'\', id: '.$infoItem['id'].', price: \''.(($infoItem['price_1']!=$infoItem['price_2'] AND $infoItem['price_2']!=0) ? $infoItem['price_2'] : $infoItem['price_1']).'\', brand: \''.getOneValueText($infoItem['select_1']).'\', category: \''.getOneValueText($infoItem['select_2']).'\'});
        var idItem = '.intval($_GET['id']).';
        $.ajax({
            type: \'POST\',
            dataType: \'html\',
            url: main_site + \'include/ajax/addItemToCart.php\',
            data: {
                idItem: idItem
            },
            success: function(result) {
                $("#addToCartModalBody").html(result);
                $("#addToCartModal").modal("show");
                getCartBlock();
            },
        });
    });
});
function setMainImage(id)
{
    $.ajax({
        type: \'POST\',
        dataType: \'html\',
        url: main_site + \'include/ajax/getMainImage.php\',
        data: {
            id: id
        },
        success: function(result) {
            $("#mainImage").html(result);
        },
    });
}
function setMainVideo(id)
{
    $("#mainImage").html(\'<iframe width="600" height="384" src="https://www.youtube.com/embed/\' + id + \'" frameborder="0" allowfullscreen></iframe>\');
}
';
$video = '';
if (strlen($infoItem['text_8'])>0){
    $explodeYt = explode ('v=', $infoItem['text_8']);
    //$smallImage .= '<div class="oneImageSmall" style="cursor:pointer;"><img src="https://i.ytimg.com/vi/'.$explodeYt[1].'/default.jpg" width="106" height="106"  onclick="setMainVideo(\''.$explodeYt[1].'\');"></div>';
    if (MOBILEVER==0){
        $video = '<iframe width="600" height="384" src="https://www.youtube.com/embed/'.$explodeYt[1].'" frameborder="0" allowfullscreen></iframe>';
    } else {
        $video = '<iframe width="300" height="254" src="https://www.youtube.com/embed/'.$explodeYt[1].'" frameborder="0" allowfullscreen></iframe>';
    }
}
//echo MOBILEVER;
if (!empty($infoItem['text_12'])){
    if (!empty($infoItem['select_29']) and $infoItem['select_29']!=0){
        $typeSize = '29';
    } else {
        $typeSize = '28';
    }
    $sql = "
        SELECT
            `ls_items`.*
        FROM
            `ls_items`
        LEFT JOIN
            `ls_params_select_values`
        ON
            `ls_params_select_values`.`id` = `ls_items`.`select_$typeSize`
        LEFT JOIN
            `ls_translate`
        ON `ls_params_select_values`.`id` = `ls_translate`.`id_elements`

        WHERE
            `ls_items`.`text_12` = '".$infoItem['text_12']."'
        AND
            `ls_translate`.`type` = 'select_value'
        AND
            `ls_items`.`select_15` = 12 ORDER by `ls_translate`.`text`";
    if ($arrayOtherSize = getArray($sql)){
        $otherSize = '<div class="descType">Выберите размер</div>
        <input type="hidden" id="idItemSize" value="'.$infoItem['id'].'">
        ';
        foreach ($arrayOtherSize as $oneItemSize){
            $active = '';
            if ($oneItemSize['id']==$infoItem['id']){
                $active = ' oneSizeItemActive';
            }
//            if ($oneItemSize['price_2']==0 or $oneItemSize['price_1']==$oneItemSize['price_2'])
//            {
//                $priceOtherSize = $infoItem['price_1'];
//            } else {
//                $priceOtherSize = $infoItem['price_2'];
//            }
            if (intval($oneItemSize['price_2'])==0)
                $oneItemSize['price_2'] = $oneItemSize['price_1'];
            $otherSize .= '<div class="oneSizeItem'.$active.'" data-placement="top" rel="tooltip" id="'.$oneItemSize['id'].'">'.getOneValueText($oneItemSize['select_'.$typeSize]).'</div><input type="hidden" id="priceId_'.$oneItemSize['id'].'" value="'.$oneItemSize['price_2'].'"><input type="hidden" id="priceOldId_'.$oneItemSize['id'].'" value="'.$oneItemSize['price_1'].'">';
        }
    }
} else {
    $otherSize = '<input type="hidden" id="idItemSize" value="0">';
}
//$infoParentItem = getOneString("SELECT * FROM ``")
$infoLastItem = getOneString("SELECT `id` FROM `ls_items` ORDER by `id` DESC LIMIT 0,1");
if ($infoItem['price_2']!=0 and $infoItem['price_2']!=$infoItem['price_1']){
    $addAct = '<div style="position: absolute; top: 0px; left: 0px; padding: 5px 15px; text-align: center; background-color: rgba(240,0,9,0.7); color: #FFF; font-size: 1.2em;"> Акція!</div>';
}
if ($infoItem['select_32']==451){
    $addAct = '<div style="position: absolute; top: 0px;  left: 0px; padding: 5px 15px; text-align: center; background-color: rgba(240,211,0,0.69); color: #FFF; font-size: 1.2em;"> OUTLET</div>';
}
//    $addAct = $infoLastItem['id'].'-'.$v['id'];
if ($infoLastItem['id']<($infoItem['id']+20)){
    $addAct = '<div style="position: absolute;  top: 0px; left: 0px; padding: 5px 15px; text-align: center; background-color: rgba(59,240,78,0.68);  color: #FFF; font-size: 1.2em;"> Новинка!</div>';
}
if ($infoItem['text_13']==5){
    $addAct = '<div style="position: absolute; top: 0px;  left: 0px; padding: 5px 15px; text-align: center; background-color: rgba(240,52,0,0.67); color: #FFF; font-size: 1.2em;"> Товар закінчується</div>';
}
$imgStyle = '';
if ($infoItem['select_15']==758){
    $imgStyle = ' style="opacity: 0.5; -webkit-filter: grayscale(100%); -moz-filter: grayscale(100%); -ms-filter: grayscale(100%); -o-filter: grayscale(100%); filter: grayscale(100%);             filter: gray; /* IE 6-9 */" ';
    $priceHtml = 'Немає в наявності';
    $disabled = ' disabled';
}
$similarItems = '';
$sql = "SELECT `ls_items`.* FROM `ls_items` WHERE `select_1` = '".$infoItem['select_1']."'  AND `select_5` != 78 AND `id` != '".$infoItem['id']."' GROUP by `text_1` LIMIT 0,10";
if ($array_items = getArray($sql))
{
    $htmlTemplate = file_get_contents('templates/'.$config ['default_template'].'/similarOneItem.html');
    $i = 0;
    $keyMobile = 4;
    foreach ($array_items as $key => $v)
    {
        $oneItem = $htmlTemplate;

        $oneItem = getOneItem($v, $oneItem);
        $items .= $oneItem;
    }
    $similarItems = $items;
} else {
    $sql = "SELECT `ls_items`.* FROM `ls_items` WHERE `select_5` != 78 AND `id` != '".$infoItem['id']."'  GROUP by `text_1` ORDER by RAND() LIMIT 0,10";
    if ($array_items = getArray($sql))
    {
        $htmlTemplate = file_get_contents('templates/'.$config ['default_template'].'/similarOneItem.html');
        $i = 0;
        $keyMobile = 4;
        foreach ($array_items as $key => $v)
        {
            $oneItem = $htmlTemplate;

            $oneItem = getOneItem($v, $oneItem);
            $items .= $oneItem;
        }
        $similarItems = $items;
    }
}
$origin = '<meta property="og:image" content="'.getImgSoroka($v, 800, 600).'">';
if (!empty($v['text_3'])) {
    $arrayItemsColor = getColorArrayItem($v);
    $itemsColor = '<div class="descType">Доступные цвета:</div><div class="row">';
    foreach ($arrayItemsColor as $oneItem){
        $itemsColor .= '
            <div class="itemColor col-xs-2">
                <a href="https://domajor.com.ua/ru/mode/item-'.$oneItem['id'].'.html" class="thumbnail"><img src="'.getImgSoroka($oneItem, 100,100).'" alt="'.$oneItem['text_1'].' '.$oneItem['text_4'].'" width="100" height="100"></a>
            </div>
            ';
    }
    $itemsColor .= '</div>';
}
$characteristics = '';
$blockParam = Array();
$blockParam[] = 'text_1';
$blockParam[] = 'text_12';
$blockParam[] = 'text_2';
$blockParam[] = 'text_3';
$blockParam[] = 'text_6';
$blockParam[] = 'text_7';
$blockParam[] = 'text_8';
//$blockParam[] = 'text_11';
$blockParam[] = 'text_9';
$blockParam[] = 'text_13';
//    $blockParam[] = 'select_1';
$blockParam[] = 'select_2';
//$blockParam[] = 'select_6';
$blockParam[] = 'select_3';
$blockParam[] = 'select_8';
$blockParam[] = 'select_7';
$blockParam[] = 'select_9';
$blockParam[] = 'select_18';
$blockParam[] = 'select_20';
$blockParam[] = 'select_21';
$blockParam[] = 'select_22';
$blockParam[] = 'select_23';
$blockParam[] = 'select_25';
$blockParam[] = 'select_26';
$blockParam[] = 'select_27';
$blockParam[] = 'select_32';
$blockParam[] = 'select_34';
$blockParam[] = 'select_10';
$blockParam[] = 'select_12';
$blockParam[] = 'select_11';
$blockParam[] = 'select_14';
//$blockParam[] = 'select_12';
$characteristics .= '
        <table class="table table-bordered table-striped">
        ';
$buttonBuyEnable = 1;
foreach ($infoItem as $key => $oneP){
    if (!in_array($key, $blockParam) and $oneP!=0 and !empty($oneP)){
        $type = '';
        if (substr_count($key,'select')>0){
            $type = 'select';
        }
        if (substr_count($key,'text')>0){
            $type = 'text';
        }
        $trueKey = str_replace('select_', '', $key);
        $trueKey = str_replace('select_', '', $trueKey);
        $stop = 0;
        switch($type){
            case "select":
                $tmp = return_name_for_id_select_param(1, $trueKey);
                $tmpArr = explode('/', $tmp['text']);
                $nameParam = $tmpArr[0];
                if ($trueKey==31){
                    $valueParam = getOneValueText($oneP);
                    $valueParam = str_replace('weeks', 'недель', $valueParam);
                    $valueParam = str_replace('days', 'дней', $valueParam);
                    $valueParam = str_replace('h', ' години', $valueParam);
                    $otpravka = $valueParam;
                } elseif ($trueKey==15){
                    $valueParam = getOneValueText($oneP);
                    $valueParam = str_replace('instock', 'в наличии', $valueParam);
                    $valueParam = str_replace('outofstock', 'нет в наличии', $valueParam);
                    $valueParam = str_replace('available for order', 'доступен для заказа', $valueParam);
                    $stock = $valueParam;
                } elseif($trueKey==6) {
                    if ($infoItem['text_7']==0 AND $infoItem['text_12']==0){
                        if ($infoItem['select_12']==215){
                            $valueParam = getOneValueText($oneP);
                            $stock = 'під замовлення';
                            $otpravka = $valueParam;
                        } else {
                            $valueParam = '<span style="color:red;">немає в наявності</span>';
                            $stock = $valueParam;
                            $otpravka = '-';
                            $buttonBuyEnable = 0;
                        }
                    } elseif($infoItem['text_7']==-1 AND $infoItem['text_12']==0) {
                        $valueParam = '<span style="color:red;">немає в наявності</span>';
                        $stock = $valueParam;
                        $otpravka = '-';
                    } else {
                        $valueParam = getOneValueText($oneP);
                        $otpravka = $valueParam;
                        $stock = 'В наявності';
                    }

                } elseif ($trueKey==1) {
                    $valueParam = '<a href="https://domajor.com.ua/ua/shop/Brand/?param&select[1][]='.$infoItem['select_1'].'&sort=popular" target="_blank">'.getOneValueText($oneP).'</a>';
                } else {
                    $valueParam = getOneValueText($oneP);

                }
                break;
            case "text":
                $trueKey = str_replace('text_', '', $key);
                $tmp = return_name_for_id_text_param(1, $trueKey);
                $nameParam = $tmp['text'];
                $valueParam = $oneP;
                break;
            default:
                $stop = 1;
        }
        if ($stop==0) {
            $characteristics .= '
                <tr>
                    <td>' . $nameParam . '</td>
                    <td>' . $valueParam . '</td>
                </tr>
                ';
        }
    }
}
$characteristics .= '
        </table>
        ';
$infoCategory = getOneString("SELECT * FROM `ls_params_select_values` WHERE `id` = '".$infoItem['select_2']."';");
$parentParam = '<li><a href="https://domajor.com.ua/ru/shop/'.translit(getOneValueText($infoCategory['parent_param_id'])).'/?param&select[2][]='.$infoCategory['parent_param_id'].'&sort=popular">'.getOneValueText($infoCategory['parent_param_id']).'</a></li>';
//$origin = '<meta property="og:image" content="'.getImgSoroka($infoItem, 1280, 800).'">';
$origin = '<meta property="og:image" content="'.$config ['site_url'].'upload/userparams/'.getMainImage ($infoItem['id']).'">';

    $mobileCarousel = '
<div class="row content-mobile">
                <div class="col-xs-12">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                                <!-- Wrapper for slides -->
                                <div class="carousel-inner" role="listbox">
                                    
                                '.$smallImageMobile.'
        
                                </div>
                                <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                    <span class="sr-only">Previous</span>
                                </a>
                                <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </div>
                            </div>
                            </div>
    ';
if ($arrayOtherColor = getArray("SELECT * FROM `ls_itemToItemOtherColor` WHERE `idItem` = '".$infoItem['id']."'")){
    $otherColorBlock = '
    <div class="row" style="margin-top:2em;">
        <div class="col-lg-12">
            <div style="color: #fe2a1e;font-size: 1.2em;">Інші кольори</div>
        </div>
    </div>
    <div class="row" style="margin-top:1em;">
    ';
    foreach ($arrayOtherColor as $oneColor){
        $item2 = getOneString("SELECT * FROM `ls_items` WHERE `id` = '".$oneColor['idItem2']."'");
        if ($item2['text_7']>0 or $item2['text_12']>0) {
            $otherColorBlock .= '
        <div class="col-lg-2 col-xs-6">  
            <a href="' . getItemLink($item2) . '" class="thumbnail">
                <img src="' . getImgSoroka($item2, 100, 100) . '" alt="' . $item2['text_1'] . '">
            </a>
        </div>
        ';
        }
    }
    $otherColorBlock .= '</div>';
}
if (MOBILEVER==1 AND $buttonBuyEnable==1)
    $buttonBuy = '<div style="position: fixed; bottom:0; width:100%;"><button class="btn btn-info btn-lg addToCart" style="width:100%;" '.$disabled.'>Купити</button></div>';
//{"@type": "Review","reviewRating": {"@type": "Rating","ratingValue": "4","bestRating": "5"},"author": {"@type": "Person","name": "Алекс"}}
//"review":[ ,{"@type": "Review","reviewRating": {"@type": "Rating","ratingValue": "5","bestRating": "5"},"author": {"@type": "Person","name": "Андрей"}},{"@type": "Review","reviewRating": {"@type": "Rating","ratingValue": "5","bestRating": "5"},"author": {"@type": "Person","name": "Ромка"}},{"@type": "Review","reviewRating": {"@type": "Rating","ratingValue": "5","bestRating": "5"},"author": {"@type": "Person","name": "Стасян"}} ],
//"aggregateRating": {"@type": "AggregateRating","ratingValue": "4.8","reviewCount": "4"},
if ($arrayReview = getArray("SELECT * FROM `ls_reviews` WHERE `idItem` = '".$infoItem['id']."' AND `idQuestion` = 0")){
    $arrayJson = Array();
    $countRating = 0;
    foreach ($arrayReview as $key => $oneReview){
        $arrayJson[$key]['@type'] = 'Review';
        $oneReviewRating = Array();
        $oneReviewRating['@type'] = 'Rating';
        $oneReviewRating['ratingValue'] = $oneReview['rating'];
        $oneReviewRating['bestRating'] = 5;
        $oneAuthor = Array();
        $oneAuthor['@type'] = 'Person';
        $oneAuthor['name'] = $oneReview['name'];
        $arrayJson[$key]['reviewRating'] = $oneReviewRating;
        $arrayJson[$key]['author'] = $oneAuthor;
        $countRating = $countRating+$oneReview['rating'];
    }
    $aggregateRating = '"aggregateRating": {"@type": "AggregateRating","ratingValue": "'.(round($countRating/count($arrayReview),1)).'","reviewCount": "'.count($arrayReview).'"},';
}
$gift = '';
if ($arrayGift = getArray("SELECT * FROM `ls_giftToItem` WHERE `itemId` = '".$infoItem['id']."' AND `price` != '0.01'")){
    $gift = '
    <div class="row">
        <div class="col-lg-12" style="background-color: #12aedf; color:#FFF;-webkit-border-top-left-radius: 5px;
-webkit-border-top-right-radius: 5px;
-moz-border-radius-topleft: 5px;
-moz-border-radius-topright: 5px;
border-top-left-radius: 5px;
border-top-right-radius: 5px;">
            Разом дешевше! Лише з цим товаром купуйте наступні за спеціальною ціною:
        </div>    
    </div>
    <div class="row" style="margin-bottom: 20px; margin-top: 20px;">';
    $oneItem = file_get_contents('templates/'.$config ['default_template'].'/oneItemGift.html');
    foreach ($arrayGift as $oneGift){
        $item = getOneString("SELECT * FROM `ls_items` WHERE `id` = '".$oneGift['giftId']."';");
        $item['price_2'] = $oneGift['price'];
        $gift .= getOneItem($item, $oneItem);
    }
    $gift .= '</div>';
}
$giftFree = '';
if ($arrayGift = getArray("SELECT * FROM `ls_giftToItem` WHERE `itemId` = '".$infoItem['id']."' AND `price` = '0.01'")){
    $giftFree = '
    <div class="row">
        <div class="col-lg-12" style="-webkit-border-top-left-radius: 5px;
-webkit-border-top-right-radius: 5px;
-moz-border-radius-topleft: 5px;
-moz-border-radius-topright: 5px;
border-top-left-radius: 5px;
border-top-right-radius: 5px;">
        </div>    
    </div>
    <div class="row" style="margin-bottom: 20px;">
    ';
    $oneItem = file_get_contents('templates/'.$config ['default_template'].'/oneItemGiftFree.html');
    foreach ($arrayGift as $oneGift){
        $item = getOneString("SELECT * FROM `ls_items` WHERE `id` = '".$oneGift['giftId']."';");
        $item['price_2'] = $oneGift['price'];
        $giftFree .= getOneItem($item, $oneItem);
    }
    $giftFree .= '</div>';
}
if (isset ($_GET['sRegenerate'])){
    session_regenerate_id(true);
}
//session_regenerate_id
//if ($_COOKIE['accessLevel']!=100) {
//    $gift = '';
//    $giftFree = '';
//}
/*
 *  // Carousel
 * $( document ).ready(function() {

    $(".carousel").carousel({
        interval: false,
        pause: true
    });

    $( ".carousel .carousel-inner" ).swipe( {
    swipeLeft: function ( event, direction, distance, duration, fingerCount ) {
        this.parent( ).carousel( 'next' );
    },
    swipeRight: function ( ) {
        this.parent( ).carousel( 'prev' );
    },
    threshold: 0,
    tap: function(event, target) {
        window.location = $(this).find('.carousel-item.active a').attr('href');
    },
    excludedElements:"label, button, input, select, textarea, .noSwipe"
    } );

    $('.carousel .carousel-inner').on('dragstart', 'a', function () {
        return false;
    });

});
 */
$js_script .= '

   
function ShowModalOneClick(){
    if ($("#userPhone").val().length>0){
        $("#buyOneClickModal").modal("show");
    } else {
        alert ("Введите свой номер мобильного!");
    }
}
function buyOneClick(){
    var param;
        var j = 0;
        $(".sizeUserBuyOneClick").each(function(i, elem){
            if ($(this).val()==1)
            {
                param = ($(this).attr("name"));
                j = j + 1;
            }
        });
        if (!param)
        {
            $("#selectSizeBlockBuyOne").show(150);
        } else {
            $("#selectSizeBlockBuyOne").hide(150);
        $.ajax({
            type: "POST",
            url: "'.$config['site_url'].'include/ajax/buyOneClick.php",
            data: {
                id: '.$infoItem['id'].' ,
                userPhone: $("#userPhone").val(),
                param: param,
            },
            dataType: \'html\',
            success: function(result) {
                $("#buyOneClickModalBody").html(result);
                $("#buttonBuyOneClick").remove();
            },
        });
        }

}
function sendMailFoundCheaper(){
    if ($("#userPhoneFoundCheaper").val().length<9 || $("#linkMinCost").val().length<6){
        $("#errPhoneOrLink").show(300);
    } else {
    $("#errPhoneOrLink").hide(600);
        $.ajax({
            type: "POST",
            url: "'.$config['site_url'].'index.php?mode=ajax&ajax=sendMailFoundCheaper",
            data: {
                phone: $("#userPhoneFoundCheaper").val(),
                link: $("#linkMinCost").val(),
            },
            dataType: \'html\',
            success: function(result) {
                $("#bodyFoundCheaper").html(\'<div class="alert alert-success">Спасибо! В ближайшее время с Вами свяжеться наш менеджер!</div>\');
            },
        });
    }
}';
/*<div class="row">
        <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
            <div class="my_tabs">
                <div class="tab-content tab_content_style">
                    '.$bigPhotoBlock.'
                </div>
                 <div class="blog_view_list">
                    <ul class="tab_style tab_bottom nav nav-tabs">
                        '.$smallImageBlock.'
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-lg-7 col-xs-12">
            '.$giftAll.'
            <div class="row">
                <div class="col-xs-12">

                    <h1 style="color: #333333; margin-bottom: 0px; font-size: 2em; letter-spacing:-1px;" itemprop="name">'.$infoItem['text_1'].' '.getOneValueText($infoItem['select_1']).' '.$infoItem['text_4'].' </h1>
                    '.((!empty($infoItem['text_8'])) ? '<div itemprop="description" style="margin-top: 1em;">'.$infoItem['text_8'].'</div>' : '').'
                    '.$itemsColor.'
                    '.$otherSize.'
                    <div class="row" style="margin-top: 20px;">
                        <div class="col-lg-12">
                            <div class="row">
                                <div class="col-lg-12">
                                    <table class="table table-bordered table-striped" style="margin-top: 20px;">
                                        <tr>
                                            <td>
                                            Наявність: <strong>'.$stock.'</strong></td>
                                            <td><img src="{main_sait}images/novaposhta.png" style="width: 120px;">
                                            <img src="{main_sait}images/mistexpress.png" style="height: 28px;">
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>Відправка: <strong>'.$otpravka.'</strong></td>
                                            <td><a href="https://domajor.com.ua/ru/mode/content-1.html">Умови оплати та доставки</a></td>
                                        </tr>
                                    </table>
                                </div>
                            </div>

                        </div>
                    </div>
                    '.$giftFree.'
                    <div class="row" style="margin-top: 20px;" itemprop="offers" itemscope itemtype="https://schema.org/Offer">
                        <span itemprop="priceCurrency" content="UAH"></span>
                        <div class="col-lg-12">
                            <div class="row" style="margin-bottom: 1em;">
                                <div class="col-lg-12">
                                    <div class="row">
                                        <div class="col-lg-7">
                                            <div class="priceFullItem" style="background-color: #f5f5f5;">'.$priceHtml.'</div>

                                        </div>
                                        <div class="col-lg-5" style="text-align: right;">
                                                '.(($buttonBuyEnable==1) ? '<button class="btn btn-info btn-lg addToCart" style="padding: 20px 80px; width:100%;" '.$disabled.'>Купити</button>' : '').'
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    '.$otherColorBlock.'
                </div>
            </div>
        </div>
    </div>*/
if (!empty($infoItem['text_6'])){
    $stock = '<span class="in-stock"> '.$infoItem['text_6'].'</span>';
} elseif($infoItem['select_5']==76) {
    $stock = '<span class="in-stock"> В наявності</span>';
} elseif($infoItem['select_5']==77) {
    $stock = '<span class="in-stock"> Очікується</span>';
} else {
    $stock = '<span style="color: red;"> Немає в наявності</span>';
}
$size = '';
$sql = "
        SELECT 
            `ls_items`.*
        FROM `ls_items`
        LEFT JOIN
            `ls_translate`
        ON 
            `ls_translate`.`id_elements` = `ls_items`.`select_3` AND `ls_translate`.`type` = 'select_value'
       WHERE `ls_items`.`text_1` = '".$infoItem['text_1']."' AND `ls_items`.`select_2` = '".$infoItem['select_2']."' GROUP by `ls_items`.`select_3` ORDER by `ls_translate`.`text`";
if ($arraySize = getArray($sql)){
    foreach ($arraySize as $oneSize){
        // AND `ls_items`.`select_5` != 78
        $size .= '<option value="'.$oneSize['select_3'].'" '.(($infoItem['select_3']==$oneSize['select_3']) ? 'selected' : '').' '.(($oneSize['select_5']==78 ? ' disabled' : '')).'>
                        '.getOneValueText($oneSize['select_3']).' '.(($oneSize['select_5']==78 ? '(немає в наявності)' : '')).'
                    </option>';
    }
}
if (count($arraySize)>0) {
    if (count($arraySize)>1) {
        $sizeHtml = '
        <li><span class="star_color">*</span><span class="Product_color">Розмір</span></li>
        <li>
            <select id="size" ' . $onclickSize . '  onchange="getItemByColor('.$infoItem['id'].');">
                ' . $size . '
            </select>
        </li>
        ';
    } else {
        $sizeHtml = '<input type="hidden" id="size" value="'.$infoItem['select_3'].'">';
    }
}
$color = '';
if ($arrayColors = getArray("
        SELECT 
            `ls_items`.*
        FROM `ls_items`
        LEFT JOIN
            `ls_translate`
        ON 
            `ls_translate`.`id_elements` = `ls_items`.`select_3` AND `ls_translate`.`type` = 'select_value'
       WHERE `ls_items`.`text_1` = '".$infoItem['text_1']."' AND `ls_items`.`select_5` != 78 GROUP by `ls_items`.`select_2` ORDER by `ls_translate`.`text`")){
    foreach ($arrayColors as $oneColor){
        $color .= '<option value="'.$oneColor['select_2'].'" '.(($infoItem['select_2']==$oneColor['select_2' .
                '']) ? 'selected' : '').'>'.getOneValueText($oneColor['select_2']).'</option>';
    }
}
if (count($arrayColors)>1){
    $onclickSize = ' onchange="getColors('.$infoItem['id'].')"';
}
if (count($arrayColors)>0) {
    if (count($arrayColors)>1) {
        $colorHtml = '
        <input type="hidden" id="thisColor" value="'.$infoItem['select_2'].'">
        <li><span class="star_color">*</span><span class="Product_color">Колір</span></li>
            <li>
                <select id="color" onchange="getItemByColor('.$infoItem['id'].');">
                    ' . $color . '
                </select>
            </li>
        ';
    } else {
        $colorHtml = '<input type="hidden" id="color" value="'.$infoItem['select_2'].'">';
    }
}
if (empty($arrayReview)){
    $countReview = 0;
} else {
    $countReview = count($arrayReview);
}
/*{
    "@context": "https://schema.org/",
    "@type": "Product",
    "name": "'.$infoItem['text_1'].'",
    "image": "'.getImgSoroka($infoItem, 1280, 800).'",
    "sku": "'.$infoItem['text_2'].'",
    "mpn": "'.$infoItem['text_2'].'",
    "model": "'.$infoItem['text_2'].'",
    "description": "'.str_replace(array("\r\n", "\r", "\n"), ' ',  substr(strip_tags($infoItem['text_3']), 0, 300)).'...",
    '.((!empty($infoItem['text_11'])) ? '"gtin": "'.$infoItem['text_11'].'",' : '').'
    "offers": {
        "@type": "Offer",
        "priceCurrency": "UAH",
        "priceValidUntil": "'.date('Y-m-d').'",
        "url": "https://domajor.com.ua/ua/mode/item-'.$infoItem['id'].'.html",
        "price": '.$infoItem['price_1'].',
        "itemCondition": "https://schema.org/NewCondition",
        "seller": {
            "@type": "Organization",
            "name": "https://domajor.com.ua"
        },
        "availability": "https://schema.org/InStock"
    },
    "brand": {
        "@type": "brand",
        "name": "'.getOneValueText($infoItem['select_4']).'"
    },
    '.((!empty($arrayJson)) ? '"review": '.json_encode($arrayJson).',' : '').'
    '.$aggregateRating.'
}*/
$body = '
<script data-n-head=\'true\' name=\'product_structured_data\' type=\'application/ld+json\'>
                {
    "@context": "https://schema.org/",
    "@type": "Product",
    "name": "'.$infoItem['text_1'].'",
    "image": "'.getImgSoroka($infoItem, 1280, 800).'",
    "description": "'.addslashes($infoItem['text_7']).'",
    '.((!empty($infoItem['text_11'])) ? '"gtin": "'.$infoItem['text_11'].'",' : '').'
    "offers": {
        "@type": "Offer",
        "priceCurrency": "UAH",
        "priceValidUntil": "'.date('Y-m-d').'",
        "url": "https://domajor.com.ua/ua/mode/item-'.$infoItem['id'].'.html",
        "price": '.$infoItem['price_1'].',
        "itemCondition": "https://schema.org/NewCondition",
        "seller": {
            "@type": "Organization",
            "name": "https://domajor.com.ua"
        },
        "availability": "https://schema.org/InStock"
    },
    "brand": {
        "@type": "brand",
        "name": "'.getOneValueText($infoItem['select_4']).'"
    },
    '.((!empty($arrayJson)) ? '"review": '.json_encode($arrayJson).',' : '').'
    '.$aggregateRating.'
    "sku": "'.$infoItem['text_2'].'",
    "mpn": "'.$infoItem['text_2'].'",
    "model": "'.$infoItem['text_2'].'"
}

</script>
<div class="modal fade" id="buyOneClickModal">
<div class="modal-dialog">
<div class="modal-content">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Купить '.$infoItem['text_1'].' в один клик</h3>
  </div>
  <div class="modal-body" id="buyOneClickModalBody">
    <div class="selectColorItemHeader">Выберите размер</div>
        '.$allSizeBuyOneClick.'
    <div style="text-align: center; display:none; color: #FF0000; font-weight: bold;" id="selectSizeBlockBuyOne">Выберете размер, для покупки</div>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn btn-primary" onclick="ga(\'buy\', \'event\', \'quickly\', \'buy\');  buyOneClick();" id="buttonBuyOneClick">Купить</a>
  </div>
</div>
</div>
</div>
<div class="modal fade" id="addToCartModal">
<div class="modal-dialog">
<div class="modal-content">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Товар успішно додано до кошика</h3>
  </div>
  <div class="modal-body" id="addToCartModalBody">

  </div>
</div>
</div>
</div>
<div class="breadcrumbs_area">
<div class="container">
<div class="row" style="margin-bottom: 5px;">
        <div class="col-lg-12">
            <div class="breadcrumb-single breadcrumb_top">
                <ul id="breadcrumbs">
                    <li><a href="{main_sait}"><i class="fa fa-home"></i>Головна</a></li>
                    <li><span>|</span></li>
                    <li><a href="{main_sait}ua/shop/'.translit(getOneValueText($infoItem['select_1'])).'/?p='.$infoItem['select_1'].'">'.getOneValueText($infoItem['select_1']).'</a></li>
                    <li><span>|</span></li>
                    <li>'.$infoItem['text_1'].'</li>
                </ul>
            </div>
        </div>
    </div>
</div>
</div>
<div class="blog_single_view_area">
<div class="container" style="margin-top: 10px;">
    
    <div class="row">
				<div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
					<div class="my_tabs">
						<div class="tab-content tab_content_style">
							'.$bigPhotoBlock.'
						</div>
						<div class="blog_view_list">
							<ul class="tab_style tab_bottom nav nav-tabs">
								'.$smallImageBlock.'
							</ul>
						</div>
					</div>
				</div>
				<div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
					<div class="blog_product_details">
						<h2 class="blog_heading"><a href="#">'.$infoItem['text_1'].'</a></h2>
						<div class="product_rating">
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
						</div>
						<div class="product_rating">
							<a href="#">'.$countReview.' відгук(ів) <span>I</span></a>
							<a href="#detailItem"> Залишити відгук</a>
						</div>
						<div class="pricing_rate">
							<p class="stack">Наявність: '.$stock.'</p>
							<p class="stack" style="padding: 0;">Артикул: '.$infoItem['text_2'].'</p>
							'.$priceHtml.'
						</div>
					</div>
					<div class="product_options_area">
						<div class="product_options_selection">
						    '.((!empty($arraySize) or !empty($arrayColors)) ? '<ul id="options_selection">
							    '.$sizeHtml.'
								'.$colorHtml.'
							</ul>' : '').'
							
						</div>
						<div id="addToItemHtml"></div>
						'.(($infoItem['select_5']!=78) ? '<div class="cart_blog_item">
							<div class="add-to-cart">
								<input type="text" title="Qty" value="1" class="qty" id="number">
								<button type="button" title="Add to Cart" class="cart_button" onclick="addItemToCartWithVerification('.$infoItem['id'].');"><span>В корзину</span></button>
							</div>
						</div>' : '').'
					</div>
				</div>
			</div>
</div>
</div>
<div class="product_collateral_area">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="my_tabs_description" id="detailItem">
						<ul class="tab_style nav nav-tabs border-0">
							<li>
								<a class="active" data-bs-toggle="tab" href="#tab-5">Опис</a>
							</li>
							<li>
								<a data-bs-toggle="tab" href="#reviews" class="">Відгуки</a>
							</li>
						</ul>
						<div class="tab-content tab_content_style">
							<div id="tab-5" class="tab-pane fade active show">
								<div class="product_description">
									'.$infoItem['text_3'].'
								</div>
							</div>
							<div id="reviews" class="tab-pane fade">
								<div class="product_description">
									
									<div class="fieldsets">
										<h3>Ваш відгук про: <span>'.$infoItem['text_1'].'</span></h3>
										<h4>Що думаєте про цей продукт?*</h4>
                                        '.generateReview($infoItem['id']).'
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="upsell_products">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="feature_text feature_upsell">
						<h4>Схожі товари</h4>
					</div>
					<div class="m-lr-n-15px">
					    <div class="upsell_product_list">
							    '.$similarItems.'
                        </div>
					</div>
				</div>
			</div>
		</div>
	</div>
'.$admin_menu;
$priceArray = getPriceArray($infoItem);
if (isset($priceArray['priceOld'])){
    $priceBlock = '
    <del>'.$priceArray['priceOld'].'</del>
    <span>'.$priceArray['price'].' грн.</span>
    ';
} else {
    $priceBlock = '
    <span>'.$priceArray['price'].' грн.</span>
    ';
}
$body = '
<script data-n-head=\'true\' name=\'product_structured_data\' type=\'application/ld+json\'>
                {
    "@context": "https://schema.org/",
    "@type": "Product",
    "name": "'.getNameItem($infoItem).'",
    "image": "'.getImgSoroka($infoItem, 1280, 800).'",
    "description": "",
    '.((!empty($infoItem['text_5'])) ? '"gtin": "'.$infoItem['text_5'].'",' : '').'
    "offers": {
        "@type": "Offer",
        "priceCurrency": "UAH",
        "priceValidUntil": "'.date('Y-m-d').'",
        "url": "https://domajor.com.ua/ua/mode/item-'.$infoItem['id'].'.html",
        "price": '.$infoItem['price_1'].',
        "itemCondition": "https://schema.org/NewCondition",
        "seller": {
            "@type": "Organization",
            "name": "https://domajor.com.ua"
        },
        "availability": "https://schema.org/InStock"
    },
    "brand": {
        "@type": "brand",
        "name": "'.getOneValueText($infoItem['select_3']).'"
    },
    '.((!empty($arrayJson)) ? '"review": '.json_encode($arrayJson).',' : '').'
    '.$aggregateRating.'
    "sku": "'.$infoItem['text_5'].'",
    "mpn": "'.$infoItem['text_5'].'",
    "model": "'.$infoItem['text_1'].'"
}

</script>
<section class="breadcrumb__area pt-60 tp-breadcrumb__bg" data-background="" style="">
 <div class="container">
    <div class="row align-items-center">
       <div class="col-xl-7 col-lg-12 col-md-12 col-12">
          <div class="tp-breadcrumb">
             <div class="tp-breadcrumb__link mb-10">
                <span class="breadcrumb-item-active"><a href="'.$config['site_url'].'">Головна</a></span>
                <span class="breadcrumb-item"><a href="{main_sait}ua/shop/'.translit(getOneValueText($infoItem['select_1'])).'/?p='.$infoItem['select_1'].'">'.getOneValueText($infoItem['select_1']).'</a></span>
                '.((!empty($infoItem['select_2'] AND $infoItem['select_2']!=0) ? '
                <span class="breadcrumb-item"><a href="{main_sait}ua/shop/'.translit(getOneValueText($infoItem['select_1']).'_'.getOneValueText($infoItem['select_2'])).'/?p='.$infoItem['select_1'].','.$infoItem['select_2'].'">'.getOneValueText($infoItem['select_2']).'</a></span>
                ' : '')).'
                '.((!empty($infoItem['select_3'] AND $infoItem['select_3']!=0) ? '
                <span class="breadcrumb-item"><a href="{main_sait}ua/shop/'.translit(getOneValueText($infoItem['select_1']).'_'.getOneValueText($infoItem['select_2']).'_'.getOneValueText($infoItem['select_3'])).'/?p='.$infoItem['select_1'].','.$infoItem['select_2'].','.$infoItem['select_3'].'">'.getOneValueText($infoItem['select_3']).'</a></span>
                ' : '')).'
                <span>'.getNameItem($infoItem).'</span>
             </div>
             <h2 class="tp-breadcrumb__title">'.getNameItem($infoItem).'</h2>
          </div>
       </div>
    </div>
 </div>
</section>
<div class="product-area pt-80 pb-50">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-12">
              <div class="tpproduct-details__list-img">
                 '.$blockImage.'
              </div>
            </div>
            <div class="col-lg-6 col-md-7">
                  <div class="tpproduct-details__content tpproduct-details__sticky">
                     <div class="tpproduct-details__tag-area d-flex align-items-center mb-5">
                        <span class="tpproduct-details__tag">'.getOneValueText($infoItem['select_2']).'</span> 
                        <div class="tpproduct-details__rating">
                           <a href="#"><i class="fas fa-star"></i></a>
                           <a href="#"><i class="fas fa-star"></i></a>
                           <a href="#"><i class="fas fa-star"></i></a>
                           <a href="#"><i class="fas fa-star"></i></a>
                           <a href="#"><i class="fas fa-star"></i></a>
                        </div>
                        <a class="tpproduct-details__reviewers">'.getCountReview($infoItem['id']).' відгуків</a>
                     </div>
                     <div class="tpproduct-details__title-area d-flex align-items-center flex-wrap mb-5">
                        <h3 class="tpproduct-details__title">'.getNameItem($infoItem).'</h3>
                        <span class="tpproduct-details__stock">'.(($infoItem['text_4'])>0 ? 'В наявності' : 'Немає в наявності').'</span>
                     </div>
                     <div class="tpproduct-details__price mb-30">
                        '.$priceBlock.'
                     </div>
                     '.(($infoItem['text_4'])>0 ? '
                     <div class="tpproduct-details__count d-flex align-items-center flex-wrap mb-25">
                        <div class="tpproduct-details__quantity">
                           <span class="cart-minus"><i class="far fa-minus"></i></span>
                           <input class="tp-cart-input" type="text" value="1" id="number">
                           <span class="cart-plus"><i class="far fa-plus"></i></span>
                        </div>
                        <div class="tpproduct-details__cart ml-20">
                           <button  onclick="addItemToCartWithVerification('.$infoItem['id'].');"><i class="fal fa-shopping-cart"></i> Додати в корзину</button>
                        </div>
                     </div>
                     ' : '').'
                     
                     <div class="tpproduct-details__information tpproduct-details__code">
                        <p>SKU:</p><span>'.$infoItem['text_5'].'</span>
                     </div>
                     <div class="tpproduct-details__information tpproduct-details__categories">
                        <p>Категорії:</p>
                        <span><a href="'.getCategoryLinkById($infoItem['select_1']).'">'.getOneValueText($infoItem['select_1']).',</a></span>
                        '.((!empty($infoItem['select_2']) AND $infoItem['select_2']!=0) ? '<span><a href="'.getCategoryLinkById($infoItem['select_2']).'">'.getOneValueText($infoItem['select_2']).',</a></span>' : '').'
                        '.((!empty($infoItem['select_3']) AND $infoItem['select_3']!=0) ? '<span><a href="'.getCategoryLinkById($infoItem['select_3']).'">'.getOneValueText($infoItem['select_3']).',</a></span>' : '').'
                     </div>
                     <div class="tpproduct-details__navtab mb-60 mt-3">
                     <div class="tpproduct-details__nav mb-30">
                        <ul class="nav nav-tabs pro-details-nav-btn" id="myTabs" role="tablist">
                           <li class="nav-item" role="presentation">
                              <button class="nav-links active" id="home-tab-1" data-bs-toggle="tab" data-bs-target="#home-1" type="button" role="tab" aria-controls="home-1" aria-selected="true">Опис</button>
                           </li>
                           <li class="nav-item" role="presentation">
                              <button class="nav-links" id="reviews-tab" data-bs-toggle="tab" data-bs-target="#reviews" type="button" role="tab" aria-controls="reviews" aria-selected="false">Відгуки ('.getCountReview($infoItem['id']).')</button>
                           </li>
                        </ul>
                     </div>
                     <div class="tab-content tp-content-tab" id="myTabContent-2">
                        <div class="tab-para tab-pane fade active show" id="home-1" role="tabpanel" aria-labelledby="home-tab-1">
                           '.str_replace('<img src=', '<img class="img-thumbnail" src=', $infoItem['text_2']).'
                        </div>
                        <div class="tab-pane fade" id="reviews" role="tabpanel" aria-labelledby="reviews-tab">
                           <div class="product-details-review">
                              <h3 class="tp-comments-title mb-35">Ваш відгук про: <span>'.getNameItem($infoItem).'</span></h3>
                              '.generateReview($infoItem['id']).'
                           </div>
                        </div>
                     </div>
                  </div>
                  </div>
               </div>        
        </div>    
    </div>
</div>
<div id="addToItemHtml"></div>
';